language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t douglasrosa16/prest_serv_front -f Dockerfile.dev .

script:
  - docker run -e CI=true douglasrosa16/prest_serv_front npm run test
