language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t douglasrosa16/prest_serv_front -f Dockerfile.dev .

script:
  - docker run -e CI=true douglasrosa16/prest_serv_front npm run test

deploy:
  provider: s3   
  bucket_name: "appfrontprest"     
  bucket_path: "appfrontprest"             
  skip_cleanup: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-west-2"