sudo: required
language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  - docker build -t douglasrosa16/prest_serv_front -f Dockerfile.dev .

script:
  - docker run douglasrosa16/prest_serv_front npm run test -- --coverage #Fazer isso para executar os testes e encerrar


