language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t douglasrosa16/prest_serv_front -f Dockerfile.dev .

script:
  - docker run -e CI=true douglasrosa16/prest_serv_front npm run test

deploy:
  provider: s3   
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
  bucket: "servmais.com1"       
  skip_cleanup: true
  region: "us-east-1"
  acl: public_read